### PR TITLE
Make role ansible 2.4 compatible

### PR DESCRIPTION
**Pull request by Yannik**
Fixes
```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks'
for dynamic inclusions. This feature will be removed in a future release.
```

### CODE REVIEW

**Comment by Yannik** [comment]
@geerlingguy Can you update your gist + dockerfile to fedora 27 so this properly works?

**Comment by runofthemill** [comment]
Was just looking into this myself, and saw an open PR. Hooray!

@Yannik I see you're waiting on @geerlingguy to update Travis for this to pass, but while you wait - it looks like there's a second `include` as noted in #42 on line 57; would you update your PR to fix that too? =D

**Comment by Yannik** [comment]
@runofthemill fixed

**Comment by runofthemill** [comment]
@Yannik looks like Travis got updated in 7be8281 - not sure if you can trigger a rebuild? If not, or @geerlingguy can you rebuild this PR?

👏🏻

**Comment by Yannik** [comment]
@runofthemill done

**Comment by runofthemill** [comment]
@geerlingguy - any chance you could take a look at this? Travis looks like it just timed out on the one test that failed. Thanks!

**Pull request merged**
